### ISSUE TITLE
Some creds resolution error

### ISSUE THREAD

**Issue by alexmozzhakov** [An0nUD4Y/SocialFish#50]
```
Traceback (most recent call last):
  File "SocialFish.py", line 279, in <module>
    waitCreds()
  File "SocialFish.py", line 156, in waitCreds
    matchObj = re.match('^(.*?),(.*)$', ipinfo['loc'])
KeyError: 'loc'
```

**Comment by alexmozzhakov** [comment]
P.S. IP was `127.0.0.1` (not a bug)
