### ISSUE TITLE
Traceback error

### ISSUE THREAD

**Issue by alexmozzhakov** [An0nUD4Y/SocialFish#63]
```
Traceback (most recent call last):
  File "SocialFish.py", line 292, in <module>
    waitCreds()
  File "SocialFish.py", line 158, in waitCreds
    ip = re.match('Victim Public IP: (.*?)\n', lines).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

```

**Comment by alexmozzhakov** [comment]
This is strange, because 
```
import re
open('Server/www/ip.txt') as creds:
             lines = creds.read().rstrip()
             if len(lines) != 0:
                 ip = re.match('Victim Public IP: (.*?)\n', lines).group(1)
```
gives no error

**Comment by alexmozzhakov** [comment]
I will assume indentation error https://github.com/An0nUD4Y/SocialFish/blob/400cd69d0ce4ac18139d83bf211489947aad107c/SocialFish.py#L154-L157
