### ISSUE TITLE
SocialFishTermux NGROK issue with architecture. 

### ISSUE THREAD

**Issue by Ublimjo** [An0nUD4Y/SocialFish#7]
Traceback (most recent call last):  
File "SocialFishTermux.py", line 214, in <module>  
    runNgrok()  
File "SocialFishTermux.py", line 205, in runNgrok  
    print('\n {0}[{1}*{0}]{1} Ngrok URL: {2}' + url.readlines()[0] + '{1}').format(CYAN, END, GREEN) IndexError:  
list index out of range

**Comment by An0nUD4Y** [comment]
wait, i am trying to resolve this issue,,,,

**Comment by usama7628674** [comment]
@Ublimjo This isn't a issue.I guess you're trying to use termux version in linux.Actually you can't cuz termux use arm version of ngrok (not amd64 or i386) which won't run in linux machine so you have to run it in your android device.Here is the screenshot of termux version running in my android device.
![screenshot_2018-04-25-09-26-00](https://user-images.githubusercontent.com/29252277/39226396-b2d2f4d8-486b-11e8-9c00-a099151e1b71.png)

**Comment by Ublimjo** [comment]
No, I use termux

**Comment by Ublimjo** [comment]
![](https://i.imgur.com/MIpMoQA.jpg)

**Comment by usama7628674** [comment]
@Ublimjo Did you execute python2 SocialFishTermux.py in your device?

**Comment by Ublimjo** [comment]
What!!    Is it possible?!?
```bash
$ ./ngrok 80
NAME:
   ngrok - tunnel local ports to public URLs and inspect traffic

DESCRIPTION:
    ngrok exposes local networked services behinds NATs and firewalls to the
    public internet over a secure tunnel. Share local websites, build/test
    webhook consumers and self-host personal services.
    Detailed help for each command is available with 'ngrok help <command>'.
    Open http://localhost:4040 for ngrok's web interface to inspect traffic.

EXAMPLES:
    ngrok http 80                    # secure public URL for port 80 web server
    ngrok http -subdomain=baz 8080   # port 8080 available at baz.ngrok.io
    ngrok http foo.dev:80            # tunnel to host:port instead of localhost
    ngrok tcp 22                     # tunnel arbitrary TCP traffic to port 22
    ngrok tls -hostname=foo.com 443  # TLS traffic for foo.com to port 443
    ngrok start foo bar baz          # start tunnels from the configuration file

VERSION:
   2.2.8

AUTHOR:
  inconshreveable - <alan@ngrok.com>

COMMANDS:
   authtoken    save authtoken to configuration file
   credits      prints author and licensing information
   http         start an HTTP tunnel
   start        start tunnels by name from the configuration file
   tcp          start a TCP tunnel
   tls          start a TLS tunnel
   update       update ngrok to the latest version
   version      print the version string
   help         Shows a list of commands or help for one command

ERROR:  Unrecognized command: ./ngrok
$
```

**Comment by Ublimjo** [comment]
No!, look 
```bash
   update       update ngrok to the latest version
   version      print the version string
   help         Shows a list of commands or help for one command

ERROR:  Unrecognized command: ./ngrok
$
```

**Comment by An0nUD4Y** [comment]
@Ublimjo Try to run ngrok with this command..
     ./ngrok http 8080

**Comment by Ublimjo** [comment]
Same error
```bash
$ ./ngrok http 8080
NAME:
   ngrok - tunnel local ports to public URLs and inspect traffic

DESCRIPTION:
    ngrok exposes local networked services behinds NATs and firewalls to the
    public internet over a secure tunnel. Share local websites, build/test
    webhook consumers and self-host personal services.
    Detailed help for each command is available with 'ngrok help <command>'.
    Open http://localhost:4040 for ngrok's web interface to inspect traffic.

EXAMPLES:
    ngrok http 80                    # secure public URL for port 80 web server
    ngrok http -subdomain=baz 8080   # port 8080 available at baz.ngrok.io
    ngrok http foo.dev:80            # tunnel to host:port instead of localhost
    ngrok tcp 22                     # tunnel arbitrary TCP traffic to port 22
    ngrok tls -hostname=foo.com 443  # TLS traffic for foo.com to port 443
    ngrok start foo bar baz          # start tunnels from the configuration file

VERSION:
   2.2.8

AUTHOR:
  inconshreveable - <alan@ngrok.com>

COMMANDS:
   authtoken    save authtoken to configuration file
   credits      prints author and licensing information
   http         start an HTTP tunnel
   start        start tunnels by name from the configuration file
   tcp          start a TCP tunnel
   tls          start a TLS tunnel
   update       update ngrok to the latest version
   version      print the version string
   help         Shows a list of commands or help for one command

ERROR:  Unrecognized command: ./ngrok
$
```

**Comment by usama7628674** [comment]
@Ublimjo Go to official ngrok website download ngrok for your architecture and rerun it

**Comment by Ublimjo** [comment]
arm or i686 ?
Because my device is i686

**Comment by An0nUD4Y** [comment]
@Ublimjo  Please verify your architecture .... use this command ..
dpkg --print-architecture

**Comment by usama7628674** [comment]
@that's what I'm trying to say your device isn't arm

**Comment by Ublimjo** [comment]
i686

**Comment by usama7628674** [comment]
@Ublimjo Yeah find arm based device.

**Comment by Ublimjo** [comment]
* download ngrok-stable-linux-arm.zip
* unzip it
* copy ngrok to socialFish/ServerTermux/
* cd socialFish/ServerTermux/

Same error

```bash
 $ ./ngrok
NAME:
   ngrok - tunnel local ports to public URLs and inspect traffic

DESCRIPTION:
    ngrok exposes local networked services behinds NATs and firewalls to the
    public internet over a secure tunnel. Share local websites, build/test
    webhook consumers and self-host personal services.
    Detailed help for each command is available with 'ngrok help <command>'.
    Open http://localhost:4040 for ngrok's web interface to inspect traffic.

EXAMPLES:
    ngrok http 80                    # secure public URL for port 80 web server
    ngrok http -subdomain=baz 8080   # port 8080 available at baz.ngrok.io
    ngrok http foo.dev:80            # tunnel to host:port instead of localhost
    ngrok tcp 22                     # tunnel arbitrary TCP traffic to port 22
    ngrok tls -hostname=foo.com 443  # TLS traffic for foo.com to port 443
    ngrok start foo bar baz          # start tunnels from the configuration file

VERSION:
   2.2.8

AUTHOR:
  inconshreveable - <alan@ngrok.com>

COMMANDS:
   authtoken    save authtoken to configuration file
   credits      prints author and licensing information
   http         start an HTTP tunnel
   start        start tunnels by name from the configuration file
   tcp          start a TCP tunnel
   tls          start a TLS tunnel
   update       update ngrok to the latest version
   version      print the version string
   help         Shows a list of commands or help for one command

ERROR:  Unrecognized command: ./ngrok
$
```

**Comment by An0nUD4Y** [comment]
@Ublimjo 

What is the difference between i686 and x86_64

Short answer:

i686 = 32-bit Intel x86 arch 
x86_64 = 64-bit Intel x86 arch

I think this one will work for you....

https://bin.equinox.io/a/iVLSfdAz1X4/ngrok-2.2.8-linux-amd64.tar.gz --> (x86_64)

https://bin.equinox.io/a/bAxP1reZDmJ/ngrok-2.2.8-linux-386.tar.gz ----> (i686)

Please recomment if it doesn't help you ...

**Comment by Ublimjo** [comment]
ngrok is working
What's the next step

**Comment by An0nUD4Y** [comment]
1. Replace the ServerTermux/ngrok with the downloaded one.
2. Then try to rerun the ./SocialFishTermux.py.

**Comment by An0nUD4Y** [comment]
And please verify the newly downloaded ngrok. If it is working or not.
Try to run this command..
./ngrok http 8080

**Comment by Ublimjo** [comment]
Looks like I can not connect
I already did 
```bash
$ ./ngrok authtoken ...
```

but

```
ngrok by @inconshreveable                                            (Ctrl+C to quit)
Session Status                reconnecting (Get https://s3.amazonaws.com/dns.ngrok.co
Version                       2.2.8                                                  Region                        United States (us)
Web Interface                 http://127.0.0.1:4041

Connections                   ttl     opn     rt1     rt5     p50     p90
                              0       0       0.00    0.00    0.00    0.00
```

**Comment by An0nUD4Y** [comment]
@Ublimjo Please try to run this ...

'$ ./ngrok http 8080 '

AND GIVE THE OUTPUT

**Comment by Ublimjo** [comment]
![](https://i.imgur.com/o2QuPHr.jpg)

**Comment by An0nUD4Y** [comment]
Now try to rerun the ngrok...

./ngrok http 80

& Give me the output.

**Comment by Ublimjo** [comment]
![](https://i.imgur.com/E9BCp46.jpg)

**Comment by An0nUD4Y** [comment]
@Ublimjo 
Try to put this ngrok into the ServerTermux/ngrok  .

Then rerun the SocialFishTermux script.

**Comment by Ublimjo** [comment]
```console
Traceback (most recent call last):
  File "SocialFishTermux.py", line 214, in <module>
    runNgrok()
  File "SocialFishTermux.py", line 205, in runNgrok
    print('\n {0}[{1}*{0}]{1} Ngrok URL: {2}' + url.readlines()[0] + '{1}').format(CYAN, END, GREEN)
IndexError: list index out of range
```

**Comment by An0nUD4Y** [comment]
Please give me the Output.... I am waiting...

**Comment by Ublimjo** [comment]
![](https://i.imgur.com/4obKeUo.jpg)

**Comment by An0nUD4Y** [comment]
@Ublimjo  THIS IS NOT THE REPO ISSUE. 

I think you should clone this repo.
https://github.com/Lexiie/SocialFish.git 

And Do the same ... move your own ngrok in the server/ngrok place...
And try to run the script...

And if it work...

I will provide you another method to run any of the webpage.

**Comment by An0nUD4Y** [comment]
And share your output......
